# frontend/Dockerfile

FROM node:18

WORKDIR /app

RUN npm install -g http-server

COPY . .

# Puerto del Front
EXPOSE 8080

# Comando para iniciar el servidor
CMD ["http-server", "-p", "8080", "--cors"]
